In [2]:
import numpy as np

In [45]:
a = np.array([[1, 2, 3, 4],
              [6, 3, 5, 2],
              [3, 0, 2, 0]]).reshape(-1, 1, 4)
b = np.array([[3, 2, 8, 9],
              [7, 9, 4, 4],
              [3, 11, 5, 2]]).reshape(-1, 1, 4)
a

array([[[1, 2, 3, 4]],

       [[6, 3, 5, 2]],

       [[3, 0, 2, 0]]])

In [46]:
c = np.concatenate((a, b), axis=1)
c

array([[[ 1,  2,  3,  4],
        [ 3,  2,  8,  9]],

       [[ 6,  3,  5,  2],
        [ 7,  9,  4,  4]],

       [[ 3,  0,  2,  0],
        [ 3, 11,  5,  2]]])

In [47]:
d = np.mean(c, axis=1)-1
d

array([[ 1. ,  1. ,  4.5,  5.5],
       [ 5.5,  5. ,  3.5,  2. ],
       [ 2. ,  4.5,  2.5,  0. ]])

In [90]:
np.argsort(d, axis=1)[:, :-4:-1]

array([[3, 2, 1],
       [0, 1, 2],
       [1, 2, 0]])

In [117]:
t = np.array([[1, 2, 3, 4, 6, 7, 8, 9],
              [6, 3, 5, 2, 1, 1, 1 ,1],
              [3, 0, 2, 0, 1, 1, 1, 1]])
d = t.tolist()
list(map(lambda x: np.random.shuffle(x), d))
d

[[2, 1, 8, 9, 6, 4, 7, 3], [6, 2, 1, 3, 1, 1, 1, 5], [3, 1, 1, 1, 1, 2, 0, 0]]

In [21]:
a = np.zeros_like(np.array([1, 2, 3, 4]), dtype=np.float64).reshape(-1, 1).tolist()
a

[[0.0], [0.0], [0.0], [0.0]]

In [22]:
c = [1, 2, 0, 3]
d = np.array([0.5, 0.7, 0.8, 0.6])

for idx_era, prob_era in zip(c, d):
    if a[idx_era] == 0.:
        a[idx_era][0] = prob_era
    else:
        a[idx_era].append(prob_era)
a

[[0.0, 0.80000000000000004],
 [0.0, 0.5],
 [0.0, 0.69999999999999996],
 [0.0, 0.59999999999999998]]

In [23]:
np.mean(a, axis=1)

array([ 0.4 ,  0.25,  0.35,  0.3 ])